//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int OrderId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> product { get; set; }
        public int id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
