//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupPoint
    {
        public PickupPoint()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public int IndexPoint { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
